# Generated by Django 4.1.3 on 2022-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('password', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
