# Generated by Django 4.1.3 on 2022-12-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bed_bedway_game_tag_remove_spendingdetail_money_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='refud',
            new_name='refund',
        ),
    ]
