# Generated by Django 4.1.3 on 2022-12-06 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_refud_bed_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='memo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
